- Implemented #13894: init.d/solr start doesn't output anything
git-svn-id: http://svn.ez.no/svn/extensions/ezfind/ezp4/trunk@3803 49f50cf4-cce6-0310-bc1e-a21d999f3d8f

diff --git a/bin/scripts/rhel/solr b/bin/scripts/rhel/solr
--- a/bin/scripts/rhel/solr
+++ b/bin/scripts/rhel/solr
@@ -17,27 +17,27 @@
 
 DESC="Solr indexing server"
 NAME=solr
-SOLR_HOME= # Insert Solr path here, example: /var/www/ezpublish/extension/ezfind/java
+SOLR_HOME= # Set solr home here (example: /var/www/ezpublish/extension/ezfind/java)
 JAVA_HOME= # Set java home here if java is not available in /usr/bin/java or /usr/local/bin/java
 
 source /etc/rc.d/init.d/functions
 
-RETVAL=0
-
-start() {
-    echo -n $"Starting $DESC ($NAME): "
-    for JAVA in "$JAVA_HOME/bin/java" "/usr/bin/java" "/usr/local/bin/java"
-      do
-      if [ -x $JAVA ]
-	  then
-	  break
-      fi
-    done
-    if [ ! -x $JAVA ]
-	then
+for JAVA in "$JAVA_HOME/bin/java" "/usr/bin/java" "/usr/local/bin/java"
+do
+	if [ -x $JAVA ]
+        then
+		break
+	fi
+done
+if [ ! -x $JAVA ]
+then
 	echo "Unable to locate java. Please set JAVA_HOME environment variable."
 	exit
-    fi
+fi
+
+RETVAL=0
+
+d_start() {
     CURRENT_DIR=`pwd`
     cd $SOLR_HOME
     daemon --check $NAME --pidfile /var/run/solr.pid nohup $JAVA -jar start.jar > /dev/null 2>&1 &
@@ -46,50 +46,91 @@ start() {
     pid=`pidof java`
     echo $pid > /var/run/solr.pid
     cd $CURRENT_DIR
-    echo
     [ $RETVAL -eq 0 ] && touch /var/lock/subsys/$NAME
     return $RETVAL
 }
 
-stop() {
-    echo -n $"Shutting down $DESC ($NAME): "
-    killproc -p /var/run/solr.pid $NAME
+d_stop() {
+    killproc -p /var/run/solr.pid $NAME >> /dev/null 2&>1
     RETVAL=$?
-    echo
     [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$NAME
     return $RETVAL
 }
 
-restart() {
-    stop
+d_restart() {
+    d_stop >> /dev/null 2&>1
     sleep 1
-    start
+    d_start >> /dev/null 2&>1
 }
 
-reload() {
-    echo -n $"Reloading $DESC ($NAME): "
-    killproc -p /var/run/solr.pid $NAME -HUP
+d_reload() {
+    killproc -p /var/run/solr.pid $NAME -HUP 2&>1
     RETVAL=$?
-    echo
     return $RETVAL
+}
+
+d_status() {
+    status -p /var/run/solr.pid $NAME >> /dev/null 2&>1
+    return $?
 }
 
 case "$1" in
   start)
-    start
+    echo " * Starting $DESC ($NAME)"
+    d_status
+    if [ $? -eq 0 ]
+    then
+      echo "   ...already running."
+    else
+      if d_start
+      then
+        echo "   ...done."
+      else
+        echo "   ...failed."
+        RETVAL=1
+      fi
+    fi
     ;;
   stop)
-    stop
+    echo " * Stopping $DESC ($NAME)"
+    if d_stop
+    then
+      echo "   ...done."
+    else
+      echo "   ...failed."
+      RETVAL=1
+    fi
     ;;
   restart)
-    restart
+    echo " * Restarting $DESC ($NAME)"
+    d_status
+    if [ $? -neq 0 ]
+    then
+      echo "   ...not running."
+      RETVAL=1
+    else
+      if d_restart
+      then
+        echo " * ...done."
+      else
+        echo " * ...failed."
+        RETVAL=1
+      fi
+    fi
     ;;
   reload)
-    reload
+    echo " * Reloading $DESC ($NAME): "
+    d_reload
+    echo "   ...done."
     ;;
   status)
-    status -p /var/run/solr.pid $NAME
-    RETVAL=$?
+    d_status
+    if [ $? -eq 0 ]
+    then
+      echo " * $DESC ($NAME) is running"
+    else
+      echo " * $DESC ($NAME) is not running"
+    fi
     ;;
   *)
     echo $"Usage: $0 {start|stop|restart|reload|status}"
