- Implemented #013894: inid.d/solr start doesn't output anything
git-svn-id: http://svn.ez.no/svn/extensions/ezfind/ezp4/trunk@3801 49f50cf4-cce6-0310-bc1e-a21d999f3d8f

diff --git a/bin/scripts/debian/solr b/bin/scripts/debian/solr
--- a/bin/scripts/debian/solr
+++ b/bin/scripts/debian/solr
@@ -1,9 +1,9 @@
 #! /bin/sh
 #
 # eZ Find init script for debian.
-# 
+#
 # Usage:
-# 
+#
 # Set the correct SOLR_HOME value, and copy this file to /etc/init.d
 # Symlink to /etc/init.d/solr to /etc/rc3.d/S70solr and /etc/rc5.d/S70solr
 #
@@ -20,7 +20,7 @@ set -e
 PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
 DESC="Solr indexing server"
 NAME=solr
-SOLR_HOME= #INSERT Solr path here, example: /var/www/ezpublish/extension/ezfind/java
+SOLR_HOME=# Replace with the java directory of your eZFind extension (example: /var/www/ezpublish/extension/ezfind/java)
 DAEMON=$SOLR_HOME/$NAME.sh
 PIDFILE=/var/run/$NAME.pid
 SCRIPTNAME=/etc/init.d/$NAME
@@ -43,19 +43,56 @@ d_start() {
 d_stop() {
 	start-stop-daemon --stop --quiet --pidfile $PIDFILE \
 		--name java
-        rm -f $PIDFILE 
+        rm -f $PIDFILE
+}
+
+#
+#	Function that checks if solr is running
+#	Returns success (0) if solr is running, failure (1) if not running
+#
+d_status() {
+    if [ -f "$PIDFILE" ] && ps `cat $PIDFILE` >/dev/null 2>&1; then
+		return 0 # EXIT_SUCCESS
+    else
+	  	return 1 # EXIT_FAILURE
+    fi
 }
 
 case "$1" in
   start)
-	echo -n "Starting $DESC: $NAME"
+	echo " * Starting $DESC: $NAME"
+	if d_status; then
+		echo "   ...$NAME is already running."
+		return 1
+	fi
 	d_start
-	echo "."
+	if d_status; then
+		echo "   ...done."
+	else
+		echo "   ...failed to start solr"
+		exit 1
+	fi
 	;;
   stop)
-	echo -n "Stopping $DESC: $NAME"
-	d_stop
-	echo "."
+	echo " * Stopping $DESC: $NAME"
+	if d_status; then
+		d_stop
+		if d_status; then
+			echo "   ...$NAME is still running."
+			exit 1
+		else
+			echo "   ...done."
+		fi
+	else
+		echo "   ...$NAME is not running."
+	fi
+	;;
+  status)
+	if d_status; then
+		echo " * $NAME is running (PID: `cat $PIDFILE`)"
+	else
+		echo " * $NAME is not running."
+	fi
 	;;
   restart|force-reload)
 	echo -n "Restarting $DESC: $NAME"
